openapi: 3.0.3
info:
  title: Banner Management API
  version: 1.0.0
  description: API for managing banners in the system
servers:
  - url: /api/v1
tags:
  - name: banners
    description: Operations related to banners
paths:
  /banners:
    $ref: './banners.yaml#/paths/~1banners'
  /banners/{id}:
    $ref: './banners.yaml#/paths/~1banners~1{id}'
  /banners/{id}/show:
    $ref: './banners.yaml#/paths/~1banners~1{id}~1show'
  /banners/views:
    $ref: './banners.yaml#/paths/~1banners~1views'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateBannerRequest:
      $ref: './components.yaml#/components/schemas/CreateBannerRequest'
    UpdateBannerRequest:
      $ref: './components.yaml#/components/schemas/UpdateBannerRequest'
    BannerResource:
      $ref: './components.yaml#/components/schemas/BannerResource'
    ShowBannerResource:
      $ref: './components.yaml#/components/schemas/ShowBannerResource'
